/// Flutter icons GIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  GIcon
///      fonts:
///       - asset: fonts/GIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class GIcon {
  GIcon._();

  static const _kFontFam = 'GIcon';
  static const String _kFontPkg = null;

  static const IconData chat = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData services = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData activity = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shop = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stores = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
